### 获取全局配置列表
GET {{baseUrl}}/sys/config/query
Content-Type: application/json
x-tenant-id: {{tenantId}}
#x-tenant-id: google
Authorization: Bearer {{tokenValue}}


### 获取用户列表
GET {{baseUrl}}/pms/user/query
Content-Type: application/json
#x-tenant-id: {{tenantId}}
x-tenant-id: apple
Authorization: Bearer {{tokenValue}}



### 获取角色数据
GET {{baseUrl}}/pms/role/query
Content-Type: application/json
#x-tenant-id: {{tenantId}}
x-tenant-id: google
Authorization: Bearer {{tokenValue}}



### 获取角色数据
GET {{baseUrl}}/server/info/hello1
Content-Type: application/json
x-tenant-id: {{tenantId}}
Authorization: Bearer {{tokenValue}}


### 获取角色数据
GET {{baseUrl}}/server/info/hello2
Content-Type: application/json
x-tenant-id: {{tenantId}}
Authorization: Bearer {{tokenValue}}


### 获取角色数据
GET {{baseUrl}}/server/info/hello3
Content-Type: application/json
x-tenant-id: {{tenantId}}
Authorization: Bearer {{tokenValue}}

