## 安全认证

### 获取验证码
###  http://localhost:18891/auth/captcha/codes?codeKey=5jXzuwcoUzbtnHNh
GET {{baseUrl}}/auth/captcha/codes?codeKey=5jXzuwcoUzbtnHNh
x-tenant-id: {{tenantId}}


### [master]密码模式登录
POST {{baseUrl}}/auth/login
Content-Type: application/json
x-tenant-id: {{tenantId}}
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0

{
  "username": "eRiiBycWxMc8F0f3RIaaSuwVW+WsgDZcYUe+xqQEJklBjIzhRVhzjlRYDjyV6si93PN8fzgqt0olvbfUOnxtHauWGNoFQndqm5Ak71eau6IIKe0Z7VeV7IntNjO18JpogmkNrjAeAIXkCWNW09gmWeBkK2oAnaVSdK0E+tdPLnJNWmioXuApPVdF6yOWXDqF/UmNtBUz/Ytm/Mg76QRUvnudb6fVrfzJ2Fd6NBN4u07pr53VrZO9mb+a9dewURVWni4p++FrQoWcM6Kc6swfGgFWGQ7+oBOgs5nURsNwpGX3A1uwcaPRUS9ILzwOyxjAfNNxIl1XkFfNnSHpBQ54Ag==",
  "password": "eRiiBycWxMc8F0f3RIaaSuwVW+WsgDZcYUe+xqQEJklBjIzhRVhzjlRYDjyV6si93PN8fzgqt0olvbfUOnxtHauWGNoFQndqm5Ak71eau6IIKe0Z7VeV7IntNjO18JpogmkNrjAeAIXkCWNW09gmWeBkK2oAnaVSdK0E+tdPLnJNWmioXuApPVdF6yOWXDqF/UmNtBUz/Ytm/Mg76QRUvnudb6fVrfzJ2Fd6NBN4u07pr53VrZO9mb+a9dewURVWni4p++FrQoWcM6Kc6swfGgFWGQ7+oBOgs5nURsNwpGX3A1uwcaPRUS9ILzwOyxjAfNNxIl1XkFfNnSHpBQ54Ag==",
  "codeKey": "5jXzuwcoUzbtnHNh",
  "codeText": "55g9"
}

> {%
client.global.set("tokenValue", response.body.data.access_token);
client.global.set("refreshToken", response.body.data.refresh_token);
%}


### 退出登录
POST {{baseUrl}}/auth/logout
Content-Type: application/json
x-tenant-id: {{tenantId}}
Authorization: Bearer {{tokenValue}}


### 刷新token
GET {{baseUrl}}/auth/refresh
Content-Type: application/json
x-tenant-id: {{tenantId}}
Authorization: Bearer {{tokenValue}}


### 获取登录的用户信息
GET {{baseUrl}}/auth/login/user
Content-Type: application/json
x-tenant-id: {{tenantId}}
Authorization: Bearer {{tokenValue}}


### 获取登录的用户菜单权限
GET {{baseUrl}}/pms/user/rights
Content-Type: application/json
x-tenant-id: {{tenantId}}
Authorization: Bearer {{tokenValue}}


### 获取当前租户所有登录的用户
GET {{baseUrl}}/pms/user/online/query
Content-Type: application/json
x-tenant-id: {{tenantId}}
Authorization: Bearer {{tokenValue}}

### 获取当前租户所有登录的用户
GET {{baseUrl}}/pms/user/query
Content-Type: application/json
x-tenant-id: {{tenantId}}
Authorization: Bearer {{tokenValue}}


### admin
### eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmNTBlY2Y4MTdmNTQ0Njc2OWRhOTYyOTg1NzI0MmI5NCJ9.gria4LT2Am27dnxk87itKvhM6M7h-5Se9Az560LIFy8


### google
### eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5ODdmMzdkMDQ0YTM0NThhYmExYWY3MzdlNTY2ZDhmNiJ9.TNCHkxi988nw7fDULA9E4J8NzJKIC11ewNASuBATzkc


